import Head from "next/head";
import LatestBlog from "../components/blog/LatestBlog";
import { useEffect, useState } from "react";
import { HiArrowNarrowDown } from "react-icons/hi";

export default function Home() {

  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
   const scrollFunc = () => {
     setScrollY(window.scrollY);
   }

   window.addEventListener("scroll", scrollFunc);
    return () => {
      window.removeEventListener("scroll", scrollFunc);
    };

  }, [])
  
  return (
    <div>
      <Head>
        <title>Curatify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <img className="w-screen h-screen" src="/bannar.jpg" alt="Curatigy" />

      <HiArrowNarrowDown className={scrollY === 0 ? "absolute bottom-4 left-1/2 z-10 invert text-3xl animate-bounce" : "invisible"}/>
      
      <img src="/meter.jpg" className="absolute opacity-30" />
      
      <LatestBlog />
      
    </div>
  );
}
